VIVADO   := /nasopt/Xilinx/Vivado/2024.1/bin/vivado
TOP_NAME := xdma_ddr4x4_top 
PART     := xcvu13p-fhgb2104-2L-e
OUTDIR   := ~/alivu13p/xdma_ddr4x4

DEPS_TCL := ./tcl/add_prjfiles.tcl
DEPS_BD  := ./tcl/system.tcl
PRJTCL   := ../common/processing.tcl 

TARGET_NAME := $(TOP_NAME)

include ../common/processing.mk
