
set_property -dict {PACKAGE_PIN AY23  IOSTANDARD  DIFF_SSTL12} [get_ports  ref_clk_100M_p ]
set_property -dict {PACKAGE_PIN BA23  IOSTANDARD  DIFF_SSTL12} [get_ports  ref_clk_100M_n ]

# 这里为了验证 bank 229/230/231/232/233 的gt管脚的时钟频率
# 参考 UG575 P351
set_property -dict {PACKAGE_PIN B11  IOSTANDARD  DIFF_SSTL12} [get_ports  bank233_B11_clk_p ]
set_property -dict {PACKAGE_PIN B10  IOSTANDARD  DIFF_SSTL12} [get_ports  bank233_B10_clk_n ]
set_property -dict {PACKAGE_PIN D11  IOSTANDARD  DIFF_SSTL12} [get_ports  bank233_D11_clk_p ]
set_property -dict {PACKAGE_PIN D10  IOSTANDARD  DIFF_SSTL12} [get_ports  bank233_D10_clk_n ]
set_property -dict {PACKAGE_PIN F11  IOSTANDARD  DIFF_SSTL12} [get_ports  bank232_F11_clk_p ]
set_property -dict {PACKAGE_PIN F10  IOSTANDARD  DIFF_SSTL12} [get_ports  bank232_F10_clk_n ]
set_property -dict {PACKAGE_PIN H11  IOSTANDARD  DIFF_SSTL12} [get_ports  bank232_H11_clk_p ]
set_property -dict {PACKAGE_PIN H10  IOSTANDARD  DIFF_SSTL12} [get_ports  bank232_H10_clk_n ]
set_property -dict {PACKAGE_PIN K11  IOSTANDARD  DIFF_SSTL12} [get_ports  bank231_K11_clk_p ]
set_property -dict {PACKAGE_PIN K10  IOSTANDARD  DIFF_SSTL12} [get_ports  bank231_K10_clk_n ]
set_property -dict {PACKAGE_PIN M11  IOSTANDARD  DIFF_SSTL12} [get_ports  bank231_M11_clk_p ]
set_property -dict {PACKAGE_PIN M10  IOSTANDARD  DIFF_SSTL12} [get_ports  bank231_M10_clk_n ]
set_property -dict {PACKAGE_PIN P11  IOSTANDARD  DIFF_SSTL12} [get_ports  bank230_P11_clk_p ]
set_property -dict {PACKAGE_PIN P10  IOSTANDARD  DIFF_SSTL12} [get_ports  bank230_P10_clk_n ]
set_property -dict {PACKAGE_PIN T11  IOSTANDARD  DIFF_SSTL12} [get_ports  bank230_T11_clk_p ]
set_property -dict {PACKAGE_PIN T10  IOSTANDARD  DIFF_SSTL12} [get_ports  bank230_T10_clk_n ]
set_property -dict {PACKAGE_PIN V11  IOSTANDARD  DIFF_SSTL12} [get_ports  bank229_V11_clk_p ]
set_property -dict {PACKAGE_PIN V10  IOSTANDARD  DIFF_SSTL12} [get_ports  bank229_V10_clk_n ]
set_property -dict {PACKAGE_PIN Y11  IOSTANDARD  DIFF_SSTL12} [get_ports  bank229_Y11_clk_p ]
set_property -dict {PACKAGE_PIN Y10  IOSTANDARD  DIFF_SSTL12} [get_ports  bank229_Y10_clk_n ]

set_property -dict {PACKAGE_PIN BB24 IOSTANDARD  LVCMOS12   } [get_ports  {led[7]}          ]
set_property -dict {PACKAGE_PIN BA24 IOSTANDARD  LVCMOS12   } [get_ports  {led[6]}          ]
set_property -dict {PACKAGE_PIN BC22 IOSTANDARD  LVCMOS12   } [get_ports  {led[5]}          ]
set_property -dict {PACKAGE_PIN BB22 IOSTANDARD  LVCMOS12   } [get_ports  {led[4]}          ]
set_property -dict {PACKAGE_PIN BC21 IOSTANDARD  LVCMOS12   } [get_ports  {led[3]}          ]
set_property -dict {PACKAGE_PIN BB21 IOSTANDARD  LVCMOS12   } [get_ports  {led[2]}          ]
set_property -dict {PACKAGE_PIN BB20 IOSTANDARD  LVCMOS12   } [get_ports  {led[1]}          ]
set_property -dict {PACKAGE_PIN BA20 IOSTANDARD  LVCMOS12   } [get_ports  {led[0]}          ]
