set_property -dict {LOC AE31 IOSTANDARD DIFF_SSTL12    } [get_ports c2_ddr4_clk_p]
set_property -dict {LOC AE32 IOSTANDARD DIFF_SSTL12    } [get_ports c2_ddr4_clk_n]
                                                         
set_property -dict {LOC Y32  IOSTANDARD LVCMOS12       } [get_ports c2_ddr4_reset_n]
set_property -dict {LOC Y31  IOSTANDARD SSTL12_DCI     } [get_ports c2_ddr4_act_n]
set_property -dict {LOC AH33 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[0]}]
set_property -dict {LOC AF34 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[1]}]
set_property -dict {LOC AD33 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[2]}]
set_property -dict {LOC AE33 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[3]}]
set_property -dict {LOC AJ34 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[4]}]
set_property -dict {LOC AD31 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[5]}]
set_property -dict {LOC AG32 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[6]}]
set_property -dict {LOC AF30 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[7]}]
set_property -dict {LOC AF32 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[8]}]
set_property -dict {LOC AE30 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[9]}]
set_property -dict {LOC AJ33 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[10]}]
set_property -dict {LOC AC32 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[11]}]
set_property -dict {LOC AF33 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[12]}]
set_property -dict {LOC AC31 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[13]}]
set_property -dict {LOC AG31 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[14]}]
set_property -dict {LOC AG34 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[15]}]
set_property -dict {LOC AH34 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_adr[16]}]
set_property -dict {LOC AC33 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_ba[0]}]
set_property -dict {LOC AC34 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_ba[1]}]
set_property -dict {LOC AD34 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_bg[0]}]
set_property -dict {LOC AB34 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_cke[0]}]
set_property -dict {LOC Y30  IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_odt[0]}]
set_property -dict {LOC AA33 IOSTANDARD SSTL12_DCI     } [get_ports {c2_ddr4_cs_n[0]}]
                                                         
set_property -dict {LOC AK31 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[0]}]
set_property -dict {LOC AG29 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[1]}]
set_property -dict {LOC AJ30 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[2]}]
set_property -dict {LOC AJ31 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[3]}]
set_property -dict {LOC AJ29 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[4]}]
set_property -dict {LOC AJ28 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[5]}]
set_property -dict {LOC AK28 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[6]}]
set_property -dict {LOC AG30 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[7]}]
set_property -dict {LOC AP33 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[8]}]
set_property -dict {LOC AM34 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[9]}]
set_property -dict {LOC AP34 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[10]}]
set_property -dict {LOC AL34 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[11]}]
set_property -dict {LOC AR33 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[12]}]
set_property -dict {LOC AM32 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[13]}]
set_property -dict {LOC AN34 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[14]}]
set_property -dict {LOC AL32 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[15]}]
                                                         
set_property -dict {LOC AW31 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[16]}]
set_property -dict {LOC AU31 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[17]}]
set_property -dict {LOC AV31 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[18]}]
set_property -dict {LOC AU32 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[19]}]
set_property -dict {LOC AT29 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[20]}]
set_property -dict {LOC AU30 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[21]}]
set_property -dict {LOC AV32 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[22]}]
set_property -dict {LOC AT30 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[23]}]
set_property -dict {LOC AP29 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[24]}]
set_property -dict {LOC AN31 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[25]}]
set_property -dict {LOC AR30 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[26]}]
set_property -dict {LOC AM31 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[27]}]
set_property -dict {LOC AN29 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[28]}]
set_property -dict {LOC AL29 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[29]}]
set_property -dict {LOC AP30 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[30]}]
set_property -dict {LOC AL30 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[31]}]
                                                         
set_property -dict {LOC BE38 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[32]}]
set_property -dict {LOC BF38 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[33]}]
set_property -dict {LOC BC38 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[34]}]
set_property -dict {LOC BD39 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[35]}]
set_property -dict {LOC BF37 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[36]}]
set_property -dict {LOC BB38 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[37]}]
set_property -dict {LOC BE37 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[38]}]
set_property -dict {LOC BC39 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[39]}]
set_property -dict {LOC BE35 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[40]}]
set_property -dict {LOC BB36 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[41]}]
set_property -dict {LOC BE36 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[42]}]
set_property -dict {LOC BA35 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[43]}]
set_property -dict {LOC BD35 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[44]}]
set_property -dict {LOC BB35 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[45]}]
set_property -dict {LOC BD36 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[46]}]
set_property -dict {LOC BC36 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[47]}]
                                                         
set_property -dict {LOC AY35 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[48]}]
set_property -dict {LOC AW34 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[49]}]
set_property -dict {LOC AY36 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[50]}]
set_property -dict {LOC AV34 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[51]}]
set_property -dict {LOC AY33 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[52]}]
set_property -dict {LOC AV33 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[53]}]
set_property -dict {LOC BA33 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[54]}]
set_property -dict {LOC AW33 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[55]}]
set_property -dict {LOC BB29 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[56]}]
set_property -dict {LOC AY31 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[57]}]
set_property -dict {LOC AY30 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[58]}]
set_property -dict {LOC BB31 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[59]}]
set_property -dict {LOC BA29 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[60]}]
set_property -dict {LOC AY32 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[61]}]
set_property -dict {LOC BA30 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[62]}]
set_property -dict {LOC BB30 IOSTANDARD POD12_DCI      } [get_ports {c2_ddr4_dq[63]}]
                                                         
                                                                                     
                                                                                     
                                                                                     
                                                                                     
                                                                                     
                                                                                     
                                                                                     
                                                                                     
                                                         
set_property -dict {LOC AJ27 IOSTANDARD POD12_DCI } [get_ports {c2_ddr4_dm_n[0]}]
set_property -dict {LOC AT33 IOSTANDARD POD12_DCI } [get_ports {c2_ddr4_dm_n[1]}]
set_property -dict {LOC AW29 IOSTANDARD POD12_DCI } [get_ports {c2_ddr4_dm_n[2]}]
set_property -dict {LOC AP31 IOSTANDARD POD12_DCI } [get_ports {c2_ddr4_dm_n[3]}]
set_property -dict {LOC BF39 IOSTANDARD POD12_DCI } [get_ports {c2_ddr4_dm_n[4]}]
set_property -dict {LOC BC34 IOSTANDARD POD12_DCI } [get_ports {c2_ddr4_dm_n[5]}]
set_property -dict {LOC BA34 IOSTANDARD POD12_DCI } [get_ports {c2_ddr4_dm_n[6]}]
set_property -dict {LOC BC31 IOSTANDARD POD12_DCI } [get_ports {c2_ddr4_dm_n[7]}]

                                                         
set_property -dict {LOC AH28 IOSTANDARD DIFF_POD12_DCI } [get_ports {c2_ddr4_dqs_t[0]}]
set_property -dict {LOC AN32 IOSTANDARD DIFF_POD12_DCI } [get_ports {c2_ddr4_dqs_t[1]}]
set_property -dict {LOC AU29 IOSTANDARD DIFF_POD12_DCI } [get_ports {c2_ddr4_dqs_t[2]}]
set_property -dict {LOC AM29 IOSTANDARD DIFF_POD12_DCI } [get_ports {c2_ddr4_dqs_t[3]}]
set_property -dict {LOC BD40 IOSTANDARD DIFF_POD12_DCI } [get_ports {c2_ddr4_dqs_t[4]}]
set_property -dict {LOC BB37 IOSTANDARD DIFF_POD12_DCI } [get_ports {c2_ddr4_dqs_t[5]}]
set_property -dict {LOC AW35 IOSTANDARD DIFF_POD12_DCI } [get_ports {c2_ddr4_dqs_t[6]}]
set_property -dict {LOC BA32 IOSTANDARD DIFF_POD12_DCI } [get_ports {c2_ddr4_dqs_t[7]}]

                                                         
set_property -dict {LOC AH29 IOSTANDARD DIFF_POD12_DCI } [get_ports {c2_ddr4_dqs_c[0]}] 
set_property -dict {LOC AN33 IOSTANDARD DIFF_POD12_DCI } [get_ports {c2_ddr4_dqs_c[1]}] 
set_property -dict {LOC AV29 IOSTANDARD DIFF_POD12_DCI } [get_ports {c2_ddr4_dqs_c[2]}]
set_property -dict {LOC AM30 IOSTANDARD DIFF_POD12_DCI } [get_ports {c2_ddr4_dqs_c[3]}]
set_property -dict {LOC BE40 IOSTANDARD DIFF_POD12_DCI } [get_ports {c2_ddr4_dqs_c[4]}]
set_property -dict {LOC BC37 IOSTANDARD DIFF_POD12_DCI } [get_ports {c2_ddr4_dqs_c[5]}] 
set_property -dict {LOC AW36 IOSTANDARD DIFF_POD12_DCI } [get_ports {c2_ddr4_dqs_c[6]}]
set_property -dict {LOC BB32 IOSTANDARD DIFF_POD12_DCI } [get_ports {c2_ddr4_dqs_c[7]}]

                                                         
set_property -dict {LOC AH32 IOSTANDARD DIFF_SSTL12_DCI} [get_ports {c2_ddr4_ck_c[0]}]
set_property -dict {LOC AH31 IOSTANDARD DIFF_SSTL12_DCI} [get_ports {c2_ddr4_ck_t[0]}]
