set_property PACKAGE_PIN BA20 [get_ports c3_data_compare_error]
set_property PACKAGE_PIN BB20 [get_ports c3_init_calib_complete]
set_property IOSTANDARD DIFF_SSTL12 [get_ports clk_in1_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports clk_in1_n]
set_property IOSTANDARD LVCMOS12 [get_ports c3_data_compare_error]
set_property IOSTANDARD LVCMOS12 [get_ports c3_init_calib_complete]
set_property PACKAGE_PIN AY23 [get_ports clk_in1_p]


set_property PACKAGE_PIN AW14 [get_ports c3_sys_clk_p]
set_property PACKAGE_PIN AV14 [get_ports {c3_ddr4_adr[0]}]
set_property PACKAGE_PIN BA14 [get_ports {c3_ddr4_adr[1]}]
set_property PACKAGE_PIN AW16 [get_ports {c3_ddr4_adr[2]}]
set_property PACKAGE_PIN AY11 [get_ports {c3_ddr4_adr[3]}]
set_property PACKAGE_PIN AV13 [get_ports {c3_ddr4_adr[4]}]
set_property PACKAGE_PIN BA15 [get_ports {c3_ddr4_adr[5]}]
set_property PACKAGE_PIN AU14 [get_ports {c3_ddr4_adr[6]}]
set_property PACKAGE_PIN AY13 [get_ports {c3_ddr4_adr[7]}]
set_property PACKAGE_PIN AU13 [get_ports {c3_ddr4_adr[8]}]
set_property PACKAGE_PIN AY15 [get_ports {c3_ddr4_adr[9]}]
set_property PACKAGE_PIN AY12 [get_ports {c3_ddr4_adr[10]}]
set_property PACKAGE_PIN AT15 [get_ports {c3_ddr4_adr[11]}]
set_property PACKAGE_PIN BA12 [get_ports {c3_ddr4_adr[12]}]
set_property PACKAGE_PIN AW15 [get_ports {c3_ddr4_adr[13]}]
set_property PACKAGE_PIN BA13 [get_ports {c3_ddr4_adr[14]}]
set_property PACKAGE_PIN AY16 [get_ports {c3_ddr4_adr[15]}]
set_property PACKAGE_PIN BB12 [get_ports {c3_ddr4_adr[16]}]
set_property PACKAGE_PIN AU15 [get_ports {c3_ddr4_ba[0]}]
set_property PACKAGE_PIN AU16 [get_ports {c3_ddr4_ba[1]}]
set_property PACKAGE_PIN AV16 [get_ports {c3_ddr4_bg[0]}]
set_property PACKAGE_PIN BB15 [get_ports {c3_ddr4_ck_t[0]}]

set_property PACKAGE_PIN AP14 [get_ports {c3_ddr4_cke[0]}]
set_property PACKAGE_PIN AR13 [get_ports c3_ddr4_act_n]
set_property PACKAGE_PIN AL15 [get_ports c3_ddr4_reset_n]
set_property PACKAGE_PIN AN13 [get_ports {c3_ddr4_odt[0]}]
set_property PACKAGE_PIN AR15 [get_ports {c3_ddr4_cs_n[0]}]


set_property PACKAGE_PIN AY26 [get_ports {c3_ddr4_dq[0]}]
set_property PACKAGE_PIN BB26 [get_ports {c3_ddr4_dq[1]}]
set_property PACKAGE_PIN AY28 [get_ports {c3_ddr4_dq[2]}]
set_property PACKAGE_PIN BA27 [get_ports {c3_ddr4_dq[3]}]
set_property PACKAGE_PIN AW28 [get_ports {c3_ddr4_dq[4]}]
set_property PACKAGE_PIN BB27 [get_ports {c3_ddr4_dq[5]}]
set_property PACKAGE_PIN AY27 [get_ports {c3_ddr4_dq[6]}]
set_property PACKAGE_PIN BA28 [get_ports {c3_ddr4_dq[7]}]
set_property PACKAGE_PIN AM16 [get_ports {c3_ddr4_dq[8]}]
set_property PACKAGE_PIN AM19 [get_ports {c3_ddr4_dq[9]}]
set_property PACKAGE_PIN AP19 [get_ports {c3_ddr4_dq[10]}]
set_property PACKAGE_PIN AM20 [get_ports {c3_ddr4_dq[11]}]
set_property PACKAGE_PIN AN16 [get_ports {c3_ddr4_dq[12]}]
set_property PACKAGE_PIN AL20 [get_ports {c3_ddr4_dq[13]}]
set_property PACKAGE_PIN AN19 [get_ports {c3_ddr4_dq[14]}]
set_property PACKAGE_PIN AL19 [get_ports {c3_ddr4_dq[15]}]


set_property PACKAGE_PIN BE25 [get_ports {c3_ddr4_dq[16]}]
set_property PACKAGE_PIN BE28 [get_ports {c3_ddr4_dq[17]}]
set_property PACKAGE_PIN BF25 [get_ports {c3_ddr4_dq[18]}]
set_property PACKAGE_PIN BF27 [get_ports {c3_ddr4_dq[19]}]
set_property PACKAGE_PIN BC27 [get_ports {c3_ddr4_dq[20]}]
set_property PACKAGE_PIN BD28 [get_ports {c3_ddr4_dq[21]}]
set_property PACKAGE_PIN BC26 [get_ports {c3_ddr4_dq[22]}]
set_property PACKAGE_PIN BE27 [get_ports {c3_ddr4_dq[23]}]
set_property PACKAGE_PIN AV18 [get_ports {c3_ddr4_dq[24]}]
set_property PACKAGE_PIN AW18 [get_ports {c3_ddr4_dq[25]}]
set_property PACKAGE_PIN AW19 [get_ports {c3_ddr4_dq[26]}]
set_property PACKAGE_PIN AY18 [get_ports {c3_ddr4_dq[27]}]
set_property PACKAGE_PIN AW20 [get_ports {c3_ddr4_dq[28]}]
set_property PACKAGE_PIN BA18 [get_ports {c3_ddr4_dq[29]}]
set_property PACKAGE_PIN AV19 [get_ports {c3_ddr4_dq[30]}]
set_property PACKAGE_PIN AY20 [get_ports {c3_ddr4_dq[31]}]


set_property PACKAGE_PIN BC13 [get_ports {c3_ddr4_dq[32]}]
set_property PACKAGE_PIN BF15 [get_ports {c3_ddr4_dq[33]}]
set_property PACKAGE_PIN BD14 [get_ports {c3_ddr4_dq[34]}]
set_property PACKAGE_PIN BE16 [get_ports {c3_ddr4_dq[35]}]
set_property PACKAGE_PIN BC14 [get_ports {c3_ddr4_dq[36]}]
set_property PACKAGE_PIN BD15 [get_ports {c3_ddr4_dq[37]}]
set_property PACKAGE_PIN BE15 [get_ports {c3_ddr4_dq[38]}]
set_property PACKAGE_PIN BD16 [get_ports {c3_ddr4_dq[39]}]
set_property PACKAGE_PIN AR28 [get_ports {c3_ddr4_dq[40]}]
set_property PACKAGE_PIN AU27 [get_ports {c3_ddr4_dq[41]}]
set_property PACKAGE_PIN AT27 [get_ports {c3_ddr4_dq[42]}]
set_property PACKAGE_PIN AV27 [get_ports {c3_ddr4_dq[43]}]
set_property PACKAGE_PIN AR27 [get_ports {c3_ddr4_dq[44]}]
set_property PACKAGE_PIN AT28 [get_ports {c3_ddr4_dq[45]}]
set_property PACKAGE_PIN AU26 [get_ports {c3_ddr4_dq[46]}]
set_property PACKAGE_PIN AV28 [get_ports {c3_ddr4_dq[47]}]


set_property PACKAGE_PIN AR18 [get_ports {c3_ddr4_dq[48]}]
set_property PACKAGE_PIN AT18 [get_ports {c3_ddr4_dq[49]}]
set_property PACKAGE_PIN AU17 [get_ports {c3_ddr4_dq[50]}]
set_property PACKAGE_PIN AR20 [get_ports {c3_ddr4_dq[51]}]
set_property PACKAGE_PIN AP20 [get_ports {c3_ddr4_dq[52]}]
set_property PACKAGE_PIN AU20 [get_ports {c3_ddr4_dq[53]}]
set_property PACKAGE_PIN AP18 [get_ports {c3_ddr4_dq[54]}]
set_property PACKAGE_PIN AT20 [get_ports {c3_ddr4_dq[55]}]
set_property PACKAGE_PIN BB19 [get_ports {c3_ddr4_dq[56]}]
set_property PACKAGE_PIN BE18 [get_ports {c3_ddr4_dq[57]}]
set_property PACKAGE_PIN BC17 [get_ports {c3_ddr4_dq[58]}]
set_property PACKAGE_PIN BF18 [get_ports {c3_ddr4_dq[59]}]
set_property PACKAGE_PIN BB17 [get_ports {c3_ddr4_dq[60]}]
set_property PACKAGE_PIN BD18 [get_ports {c3_ddr4_dq[61]}]
set_property PACKAGE_PIN BC18 [get_ports {c3_ddr4_dq[62]}]
set_property PACKAGE_PIN BF19 [get_ports {c3_ddr4_dq[63]}]


set_property PACKAGE_PIN BA25 [get_ports {c3_ddr4_dm_dbi_n[0]}]
set_property PACKAGE_PIN AN18 [get_ports {c3_ddr4_dm_dbi_n[1]}]
set_property PACKAGE_PIN BF28 [get_ports {c3_ddr4_dm_dbi_n[2]}]
set_property PACKAGE_PIN AY17 [get_ports {c3_ddr4_dm_dbi_n[3]}]
set_property PACKAGE_PIN BF14 [get_ports {c3_ddr4_dm_dbi_n[4]}]
set_property PACKAGE_PIN AV26 [get_ports {c3_ddr4_dm_dbi_n[5]}]
set_property PACKAGE_PIN AT19 [get_ports {c3_ddr4_dm_dbi_n[6]}]
set_property PACKAGE_PIN BE17 [get_ports {c3_ddr4_dm_dbi_n[7]}]

set_property PACKAGE_PIN AW25 [get_ports {c3_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN AL17 [get_ports {c3_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN BD26 [get_ports {c3_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN AV21 [get_ports {c3_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN BD13 [get_ports {c3_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN AR25 [get_ports {c3_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN AR17 [get_ports {c3_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN BC19 [get_ports {c3_ddr4_dqs_t[7]}]











