set_property -dict {LOC J26  IOSTANDARD DIFF_SSTL12    } [get_ports c1_ddr4_clk_p]
set_property -dict {LOC H26  IOSTANDARD DIFF_SSTL12    } [get_ports c1_ddr4_clk_n]

set_property -dict {LOC K26  IOSTANDARD DIFF_SSTL12_DCI} [get_ports {c1_ddr4_ck_t[0]}]
set_property -dict {LOC B29  IOSTANDARD LVCMOS12       } [get_ports c1_ddr4_reset_n]
set_property -dict {LOC A28  IOSTANDARD SSTL12_DCI     } [get_ports c1_ddr4_act_n]
set_property -dict {LOC G27  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[0]}]
set_property -dict {LOC H28  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[1]}]
set_property -dict {LOC H27  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[2]}]
set_property -dict {LOC L28  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[3]}]
set_property -dict {LOC F29  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[4]}]
set_property -dict {LOC J28  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[5]}]
set_property -dict {LOC F28  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[6]}]
set_property -dict {LOC L27  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[7]}]
set_property -dict {LOC F27  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[8]}]
set_property -dict {LOC K28  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[9]}]
set_property -dict {LOC G29  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[10]}]
set_property -dict {LOC G26  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[11]}]
set_property -dict {LOC L29  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[12]}]
set_property -dict {LOC M27  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[13]}]
set_property -dict {LOC J29  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[14]}]
set_property -dict {LOC M29  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[15]}]
set_property -dict {LOC H29  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_adr[16]}]
set_property -dict {LOC E27  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_ba[0]}]
set_property -dict {LOC E28  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_ba[1]}]
set_property -dict {LOC D28  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_bg[0]}]
set_property -dict {LOC C29  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_cke[0]}]
set_property -dict {LOC D30  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_odt[0]}]
set_property -dict {LOC B27  IOSTANDARD SSTL12_DCI     } [get_ports {c1_ddr4_cs_n[0]}]
                                                         
set_property -dict {LOC D39  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[0]}]
set_property -dict {LOC C39  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[1]}]
set_property -dict {LOC B40  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[2]}]
set_property -dict {LOC A40  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[3]}]
set_property -dict {LOC E38  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[4]}]
set_property -dict {LOC D38  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[5]}]
set_property -dict {LOC E39  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[6]}]
set_property -dict {LOC C38  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[7]}]
set_property -dict {LOC E35  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[8]}]
set_property -dict {LOC A35  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[9]}]
set_property -dict {LOC D36  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[10]}]
set_property -dict {LOC A38  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[11]}]
set_property -dict {LOC E36  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[12]}]
set_property -dict {LOC B35  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[13]}]
set_property -dict {LOC D35  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[14]}]
set_property -dict {LOC A37  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[15]}]
                                                         
set_property -dict {LOC L32  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[16]}]
set_property -dict {LOC K32  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[17]}]
set_property -dict {LOC L33  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[18]}]
set_property -dict {LOC K31  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[19]}]
set_property -dict {LOC L30  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[20]}]
set_property -dict {LOC J31  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[21]}]
set_property -dict {LOC M30  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[22]}]
set_property -dict {LOC K33  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[23]}]
set_property -dict {LOC C33  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[24]}]
set_property -dict {LOC B32  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[25]}]
set_property -dict {LOC C34  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[26]}]
set_property -dict {LOC C32  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[27]}]
set_property -dict {LOC D33  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[28]}]
set_property -dict {LOC C31  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[29]}]
set_property -dict {LOC D34  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[30]}]
set_property -dict {LOC D31  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[31]}]
                                                         
set_property -dict {LOC J36  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[32]}]
set_property -dict {LOC G37  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[33]}]
set_property -dict {LOC G34  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[34]}]
set_property -dict {LOC F34  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[35]}]
set_property -dict {LOC J35  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[36]}]
set_property -dict {LOC F37  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[37]}]
set_property -dict {LOC H34  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[38]}]
set_property -dict {LOC F35  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[39]}]
set_property -dict {LOC H32  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[40]}]
set_property -dict {LOC E32  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[41]}]
set_property -dict {LOC G31  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[42]}]
set_property -dict {LOC F32  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[43]}]
set_property -dict {LOC H31  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[44]}]
set_property -dict {LOC E33  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[45]}]
set_property -dict {LOC G32  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[46]}]
set_property -dict {LOC F33  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[47]}]
                                                         
set_property -dict {LOC V31  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[48]}]
set_property -dict {LOC U32  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[49]}]
set_property -dict {LOC U31  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[50]}]
set_property -dict {LOC T32  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[51]}]
set_property -dict {LOC T30  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[52]}]
set_property -dict {LOC T33  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[53]}]
set_property -dict {LOC U30  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[54]}]
set_property -dict {LOC R33  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[55]}]
set_property -dict {LOC R32  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[56]}]
set_property -dict {LOC N32  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[57]}]
set_property -dict {LOC N31  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[58]}]
set_property -dict {LOC N34  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[59]}]
set_property -dict {LOC R31  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[60]}]
set_property -dict {LOC P31  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[61]}]
set_property -dict {LOC N33  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[62]}]
set_property -dict {LOC P34  IOSTANDARD POD12_DCI      } [get_ports {c1_ddr4_dq[63]}]
                                                         
                                                                                     
                                                                                     
                                                                                     
                                                                                     
                                                                                     
                                                                                     
                                                                                     
                                                                                     
                                                         
set_property -dict {LOC E40  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dm_n[0]}]
set_property -dict {LOC C36  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dm_n[1]}]
set_property -dict {LOC M31  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dm_n[2]}]
set_property -dict {LOC B34  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dm_n[3]}]
set_property -dict {LOC H37  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dm_n[4]}]
set_property -dict {LOC G30  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dm_n[5]}]
set_property -dict {LOC U34  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dm_n[6]}]
set_property -dict {LOC R30  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dm_n[7]}]

                                                         
set_property -dict {LOC B39  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dqs_t[0]}]
set_property -dict {LOC B36  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dqs_t[1]}]
set_property -dict {LOC K30  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dqs_t[2]}]
set_property -dict {LOC A32  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dqs_t[3]}]
set_property -dict {LOC H36  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dqs_t[4]}]
set_property -dict {LOC J33  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dqs_t[5]}]
set_property -dict {LOC V32  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dqs_t[6]}]
set_property -dict {LOC M34  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dqs_t[7]}]

                                                         
set_property -dict {LOC A39  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dqs_c[0]}]
set_property -dict {LOC B37  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dqs_c[1]}]
set_property -dict {LOC J30  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dqs_c[2]}]
set_property -dict {LOC A33  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dqs_c[3]}]
set_property -dict {LOC G36  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dqs_c[4]}]
set_property -dict {LOC H33  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dqs_c[5]}]
set_property -dict {LOC V33  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dqs_c[6]}]
set_property -dict {LOC L34  IOSTANDARD DIFF_POD12_DCI } [get_ports {c1_ddr4_dqs_c[7]}]


set_property -dict {LOC K27  IOSTANDARD DIFF_SSTL12    } [get_ports {c1_ddr4_ck_c[0]}]
