run:
	iverilog -o simv -f tb.f
	./simv
	gtkwave simv.vcd                                                                                                                                      

clean:
	rm simv
	rm simv.vcd
