## PCIE 只需要约束时钟源以及 复位引脚，
## 其他无需约束，配置XDMA时，PCIe Block Location 选择 X0Y1 即可。
#  x1  所用通道为227
#  x4  所用通道为227
#  x8  所用通道为227 + 226
#  x16 所用通道为227 + 226/225/224

set_property PACKAGE_PIN AK10 [get_ports {pcie_ref_clk_n[0]}]
set_property PACKAGE_PIN AK11 [get_ports {pcie_ref_clk_p[0]}] 
create_clock -name pcie_sys_clk -period 10 [get_ports {pcie_ref_clk_p[0]}]

set_property PACKAGE_PIN AR26 [get_ports pcie_perst]
set_property IOSTANDARD LVCMOS12 [get_ports pcie_perst]

set_property PACKAGE_PIN BD20 [get_ports pcie_lnk_up]
set_property IOSTANDARD LVCMOS12 [get_ports pcie_lnk_up]


#=========================================================================
# 自己版本, 参考  https://github.com/fpgasystems/Coyote/blob/master/hw/constraints/u250/u250_pcie.xdc
set_property PACKAGE_PIN AV2 [get_ports {pcie_lane_rxp[12]}]
set_property PACKAGE_PIN AV1 [get_ports {pcie_lane_rxn[12]}]
set_property PACKAGE_PIN AW4 [get_ports {pcie_lane_rxp[13]}]
set_property PACKAGE_PIN AW3 [get_ports {pcie_lane_rxn[13]}]
set_property PACKAGE_PIN BA2 [get_ports {pcie_lane_rxp[14]}]
set_property PACKAGE_PIN BA1 [get_ports {pcie_lane_rxn[14]}]
set_property PACKAGE_PIN BC2 [get_ports {pcie_lane_rxp[15]}]
set_property PACKAGE_PIN BC1 [get_ports {pcie_lane_rxn[15]}]
set_property PACKAGE_PIN AP2 [get_ports {pcie_lane_rxp[8]}]
set_property PACKAGE_PIN AP1 [get_ports {pcie_lane_rxn[8]}]
set_property PACKAGE_PIN AR4 [get_ports {pcie_lane_rxp[9]}]
set_property PACKAGE_PIN AR3 [get_ports {pcie_lane_rxn[9]}]
set_property PACKAGE_PIN AT2 [get_ports {pcie_lane_rxp[10]}]
set_property PACKAGE_PIN AT1 [get_ports {pcie_lane_rxn[10]}]
set_property PACKAGE_PIN AU4 [get_ports {pcie_lane_rxp[11]}]
set_property PACKAGE_PIN AU3 [get_ports {pcie_lane_rxn[11]}]
set_property PACKAGE_PIN AK2 [get_ports {pcie_lane_rxp[4]}]
set_property PACKAGE_PIN AK1 [get_ports {pcie_lane_rxn[4]}]
set_property PACKAGE_PIN AL4 [get_ports {pcie_lane_rxp[5]}]
set_property PACKAGE_PIN AL3 [get_ports {pcie_lane_rxn[5]}]
set_property PACKAGE_PIN AM2 [get_ports {pcie_lane_rxp[6]}]
set_property PACKAGE_PIN AM1 [get_ports {pcie_lane_rxn[6]}]
set_property PACKAGE_PIN AN4 [get_ports {pcie_lane_rxp[7]}]
set_property PACKAGE_PIN AN3 [get_ports {pcie_lane_rxn[7]}]
set_property PACKAGE_PIN AF2 [get_ports {pcie_lane_rxp[0]}]
set_property PACKAGE_PIN AF1 [get_ports {pcie_lane_rxn[0]}]
set_property PACKAGE_PIN AG4 [get_ports {pcie_lane_rxp[1]}]
set_property PACKAGE_PIN AG3 [get_ports {pcie_lane_rxn[1]}]
set_property PACKAGE_PIN AH2 [get_ports {pcie_lane_rxp[2]}]
set_property PACKAGE_PIN AH1 [get_ports {pcie_lane_rxn[2]}]
set_property PACKAGE_PIN AJ4 [get_ports {pcie_lane_rxp[3]}]
set_property PACKAGE_PIN AJ3 [get_ports {pcie_lane_rxn[3]}]
set_property PACKAGE_PIN AV7 [get_ports {pcie_lane_txp[12]}]
set_property PACKAGE_PIN AV6 [get_ports {pcie_lane_txn[12]}]
set_property PACKAGE_PIN BB5 [get_ports {pcie_lane_txp[13]}]
set_property PACKAGE_PIN BB4 [get_ports {pcie_lane_txn[13]}]
set_property PACKAGE_PIN BD5 [get_ports {pcie_lane_txp[14]}]
set_property PACKAGE_PIN BD4 [get_ports {pcie_lane_txn[14]}]
set_property PACKAGE_PIN BF5 [get_ports {pcie_lane_txp[15]}]
set_property PACKAGE_PIN BF4 [get_ports {pcie_lane_txn[15]}]
set_property PACKAGE_PIN AP7 [get_ports {pcie_lane_txp[8]}]
set_property PACKAGE_PIN AP6 [get_ports {pcie_lane_txn[8]}]
set_property PACKAGE_PIN AR9 [get_ports {pcie_lane_txp[9]}]
set_property PACKAGE_PIN AR8 [get_ports {pcie_lane_txn[9]}]
set_property PACKAGE_PIN AT7 [get_ports {pcie_lane_txp[10]}]
set_property PACKAGE_PIN AT6 [get_ports {pcie_lane_txn[10]}]
set_property PACKAGE_PIN AU9 [get_ports {pcie_lane_txp[11]}]
set_property PACKAGE_PIN AU8 [get_ports {pcie_lane_txn[11]}]
set_property PACKAGE_PIN AK7 [get_ports {pcie_lane_txp[4]}]
set_property PACKAGE_PIN AK6 [get_ports {pcie_lane_txn[4]}]
set_property PACKAGE_PIN AL9 [get_ports {pcie_lane_txp[5]}]
set_property PACKAGE_PIN AL8 [get_ports {pcie_lane_txn[5]}]
set_property PACKAGE_PIN AM7 [get_ports {pcie_lane_txp[6]}]
set_property PACKAGE_PIN AM6 [get_ports {pcie_lane_txn[6]}]
set_property PACKAGE_PIN AN9 [get_ports {pcie_lane_txp[7]}]
set_property PACKAGE_PIN AN8 [get_ports {pcie_lane_txn[7]}]
set_property PACKAGE_PIN AF7 [get_ports {pcie_lane_txp[0]}]
set_property PACKAGE_PIN AF6 [get_ports {pcie_lane_txn[0]}]
set_property PACKAGE_PIN AG9 [get_ports {pcie_lane_txp[1]}]
set_property PACKAGE_PIN AG8 [get_ports {pcie_lane_txn[1]}]
set_property PACKAGE_PIN AH7 [get_ports {pcie_lane_txp[2]}]
set_property PACKAGE_PIN AH6 [get_ports {pcie_lane_txn[2]}]
set_property PACKAGE_PIN AJ9 [get_ports {pcie_lane_txp[3]}]
set_property PACKAGE_PIN AJ8 [get_ports {pcie_lane_txn[3]}]


# 章鱼版本
#set_property PACKAGE_PIN BF5 [get_ports {pcie_lane_txp[0]}]
#set_property PACKAGE_PIN BD5 [get_ports {pcie_lane_txp[1]}]
#set_property PACKAGE_PIN BB5 [get_ports {pcie_lane_txp[2]}]
#set_property PACKAGE_PIN AV7 [get_ports {pcie_lane_txp[3]}]
#set_property PACKAGE_PIN AU9 [get_ports {pcie_lane_txp[4]}]
#set_property PACKAGE_PIN AT7 [get_ports {pcie_lane_txp[5]}]
#set_property PACKAGE_PIN AR9 [get_ports {pcie_lane_txp[6]}]
#set_property PACKAGE_PIN AP7 [get_ports {pcie_lane_txp[7]}]
#set_property PACKAGE_PIN AN9 [get_ports {pcie_lane_txp[8]}]
#set_property PACKAGE_PIN AM7 [get_ports {pcie_lane_txp[9]}]
#set_property PACKAGE_PIN AL9 [get_ports {pcie_lane_txp[10]}]
#set_property PACKAGE_PIN AK7 [get_ports {pcie_lane_txp[11]}]
#set_property PACKAGE_PIN AJ9 [get_ports {pcie_lane_txp[12]}]
#set_property PACKAGE_PIN AH7 [get_ports {pcie_lane_txp[13]}]
#set_property PACKAGE_PIN AG9 [get_ports {pcie_lane_txp[14]}]
#set_property PACKAGE_PIN AF7 [get_ports {pcie_lane_txp[15]}]
#set_property PACKAGE_PIN AF2 [get_ports {pcie_lane_rxp[15]}]
#set_property PACKAGE_PIN AG4 [get_ports {pcie_lane_rxp[14]}]
#set_property PACKAGE_PIN AH2 [get_ports {pcie_lane_rxp[13]}]
#set_property PACKAGE_PIN AJ4 [get_ports {pcie_lane_rxp[12]}]
#set_property PACKAGE_PIN AK2 [get_ports {pcie_lane_rxp[11]}]
#set_property PACKAGE_PIN AL4 [get_ports {pcie_lane_rxp[10]}]
#set_property PACKAGE_PIN AM2 [get_ports {pcie_lane_rxp[9]}]
#set_property PACKAGE_PIN AN4 [get_ports {pcie_lane_rxp[8]}]
#set_property PACKAGE_PIN AP2 [get_ports {pcie_lane_rxp[7]}]
#set_property PACKAGE_PIN AR4 [get_ports {pcie_lane_rxp[6]}]
#set_property PACKAGE_PIN AT2 [get_ports {pcie_lane_rxp[5]}]
#set_property PACKAGE_PIN AU4 [get_ports {pcie_lane_rxp[4]}]
#set_property PACKAGE_PIN AV2 [get_ports {pcie_lane_rxp[3]}]
#set_property PACKAGE_PIN AW4 [get_ports {pcie_lane_rxp[2]}]
#set_property PACKAGE_PIN BA2 [get_ports {pcie_lane_rxp[1]}]
#set_property PACKAGE_PIN BC2 [get_ports {pcie_lane_rxp[0]}]

