set_property PACKAGE_PIN  AR28       [get_ports {main_iic_sda}]
set_property PACKAGE_PIN  AP26       [get_ports {main_iic_scl}]
set_property PULLUP true             [get_ports {main_iic_sda}]
set_property PULLUP true             [get_ports {main_iic_scl}]
set_property IOSTANDARD LVCMOS18     [get_ports {main_iic_sda}]
set_property IOSTANDARD LVCMOS18     [get_ports {main_iic_scl}]
